
FROM public.ecr.aws/lambda/python:3.12-x86_64

WORKDIR /app

COPY init.sh /app/
COPY entry.sh /app/

COPY requirements.txt /app/

COPY ./app/*.py /app/

RUN dnf install -y zip bash procps findutils

RUN chmod +x /app/entry.sh /app/init.sh

RUN mkdir /tmp/pip

ENTRYPOINT ["/app/entry.sh"]

CMD exec /bin/bash -c "trap : TERM INT; while [ 1 ]; do sleep 15; done & wait"
